resources:
- name: src
  type: git
  source:
    uri: https://github.com/jared-carroll/spring-boot-hello-world.git

jobs:
- name: assemble
  plan:
  - get: src
    trigger: true
  - task: assemble
    file: src/ci/assemble.yml