resources:
- name: src
  type: git
  source:
    uri: https://github.com/jared-carroll/spring-boot-hello-world.git

jobs:
- name: step-1
  plan:
    - get: src
      trigger: true
    - task: run-tests
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: sleep
          args:
          - 10
- name: step-2
  plan:
    - get: src
      passed: [step-1]
      trigger: true
    - task: run-integration-tests
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: sleep
          args:
          - 10