resources:
- name: every-10-seconds
  type: time
  source:
    interval: 10s
- name: project-src
  type: git
  source:
    uri: https://github.com/jared-carroll/spring-boot-hello-world.git

jobs:
- name: something-every-10-seconds
  plan:
    - get: every-10-seconds
      trigger: true
    - get: project-src
    - task: something
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: echo
          args:
          - hi