resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/jared-carroll/spring-boot-hello-world.git

  - name: source-code-docker-image
    type: docker-image
    source:
      repository: jaredcarroll/hi

jobs:
  - name: build-image
    plan:
      - get: source-code
        trigger: true
#      - task: step-1
#        config:
#          platform: linux
#          image_resource:
#            type: docker-image
#            source:
#              repository: busybox
#          inputs:
#            - name: source-code
#          run:
#            path: echo
#            args:
#              - hi
      - put: source-code-docker-image
        params:
          build: source-code/ci