resources:
- name: project-src
  type: git
  source:
    uri: https://github.com/jared-carroll/spring-boot-hello-world.git

jobs:
- name: some-job
  plan:
    - get: project-src
      trigger: true
    - task: do-it
      file: project-src/ci/do-it.yml
    - task: another-task
      inputs:
        name: something
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: ls
          args:
          - something